/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Main;

import Business.Configure.ConfigureASystem;
import Business.DB4OUtil.DB4OUtil;
import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Label;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rajat
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainJFrame() {
        initComponents();
        //Configuring a system from Config file
        system =ConfigureASystem.configure();
        //Configuring a system from DB4OUtil (Comment Either one to use)
      system = dB4OUtil.retrieveSystem();
        this.setSize(1366, 700);
        try {
            PopulateDataInNewsFeed();
            container.add(newsFeed);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        newsFeed = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalDeaths = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        crimeProne = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        accidentProne = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalMoney = new javax.swing.JLabel();
        mapContainer = new javax.swing.JPanel();
        northStationJPanel = new javax.swing.JPanel();
        southStationJPanel = new javax.swing.JPanel();
        roxburyJPanel = new javax.swing.JPanel();
        longwood = new javax.swing.JPanel();
        parkStreet = new javax.swing.JPanel();
        tremontStreet = new javax.swing.JPanel();
        backBay = new javax.swing.JPanel();
        lechmere = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        loginJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Main/login.png"))); // NOI18N
        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        userNameJTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        passwordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        logoutJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Main/logout.png"))); // NOI18N
        logoutJButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameJTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(loginJLabel)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(0, 153, 153));
        container.setMaximumSize(new java.awt.Dimension(700, 700));
        container.setLayout(new java.awt.CardLayout());

        newsFeed.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NEWS FEED TO STAY ATTENTIVE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("TotalNo of Deaths till Date :");

        totalDeaths.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalDeaths.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalDeaths.setText("NA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Top Crime Prone Area is :");

        crimeProne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crimeProne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crimeProne.setText("NA");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Top Accident Prone Area is :");

        accidentProne.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accidentProne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accidentProne.setText("NA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Total Money Spent By our Govt :");

        totalMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalMoney.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalMoney.setText("NA");

        mapContainer.setBackground(new java.awt.Color(255, 153, 153));

        northStationJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        northStationJPanel.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout northStationJPanelLayout = new javax.swing.GroupLayout(northStationJPanel);
        northStationJPanel.setLayout(northStationJPanelLayout);
        northStationJPanelLayout.setHorizontalGroup(
            northStationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        northStationJPanelLayout.setVerticalGroup(
            northStationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        southStationJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        southStationJPanel.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout southStationJPanelLayout = new javax.swing.GroupLayout(southStationJPanel);
        southStationJPanel.setLayout(southStationJPanelLayout);
        southStationJPanelLayout.setHorizontalGroup(
            southStationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        southStationJPanelLayout.setVerticalGroup(
            southStationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roxburyJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        roxburyJPanel.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout roxburyJPanelLayout = new javax.swing.GroupLayout(roxburyJPanel);
        roxburyJPanel.setLayout(roxburyJPanelLayout);
        roxburyJPanelLayout.setHorizontalGroup(
            roxburyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        roxburyJPanelLayout.setVerticalGroup(
            roxburyJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        longwood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        longwood.setForeground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout longwoodLayout = new javax.swing.GroupLayout(longwood);
        longwood.setLayout(longwoodLayout);
        longwoodLayout.setHorizontalGroup(
            longwoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        longwoodLayout.setVerticalGroup(
            longwoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        parkStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        parkStreet.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout parkStreetLayout = new javax.swing.GroupLayout(parkStreet);
        parkStreet.setLayout(parkStreetLayout);
        parkStreetLayout.setHorizontalGroup(
            parkStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        parkStreetLayout.setVerticalGroup(
            parkStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        tremontStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        tremontStreet.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout tremontStreetLayout = new javax.swing.GroupLayout(tremontStreet);
        tremontStreet.setLayout(tremontStreetLayout);
        tremontStreetLayout.setHorizontalGroup(
            tremontStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        tremontStreetLayout.setVerticalGroup(
            tremontStreetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        backBay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        backBay.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout backBayLayout = new javax.swing.GroupLayout(backBay);
        backBay.setLayout(backBayLayout);
        backBayLayout.setHorizontalGroup(
            backBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        backBayLayout.setVerticalGroup(
            backBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        lechmere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lechmere.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout lechmereLayout = new javax.swing.GroupLayout(lechmere);
        lechmere.setLayout(lechmereLayout);
        lechmereLayout.setHorizontalGroup(
            lechmereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        lechmereLayout.setVerticalGroup(
            lechmereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setText("North Station");

        jLabel6.setText("South Station");

        jLabel7.setText("Roxbury");

        jLabel8.setText("Back Bay");

        jLabel9.setText("Park Street");

        jLabel10.setText("Lechmere");

        jLabel12.setText("Tremont");

        jLabel14.setText("Longwood");

        javax.swing.GroupLayout mapContainerLayout = new javax.swing.GroupLayout(mapContainer);
        mapContainer.setLayout(mapContainerLayout);
        mapContainerLayout.setHorizontalGroup(
            mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapContainerLayout.createSequentialGroup()
                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(northStationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(longwood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapContainerLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7))
                            .addGroup(mapContainerLayout.createSequentialGroup()
                                .addComponent(southStationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(roxburyJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapContainerLayout.createSequentialGroup()
                                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lechmere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mapContainerLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel10)))
                                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapContainerLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(tremontStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mapContainerLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel12))))
                            .addComponent(parkStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(backBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        mapContainerLayout.setVerticalGroup(
            mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapContainerLayout.createSequentialGroup()
                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapContainerLayout.createSequentialGroup()
                                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(roxburyJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(southStationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(parkStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(northStationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapContainerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(longwood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(mapContainerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mapContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapContainerLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tremontStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(mapContainerLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lechmere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(mapContainerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout newsFeedLayout = new javax.swing.GroupLayout(newsFeed);
        newsFeed.setLayout(newsFeedLayout);
        newsFeedLayout.setHorizontalGroup(
            newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(newsFeedLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(newsFeedLayout.createSequentialGroup()
                            .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(crimeProne, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(totalDeaths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(newsFeedLayout.createSequentialGroup()
                            .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(accidentProne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        newsFeedLayout.setVerticalGroup(
            newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsFeedLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalDeaths))
                .addGap(18, 18, 18)
                .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(crimeProne))
                .addGap(18, 18, 18)
                .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(accidentProne))
                .addGap(18, 18, 18)
                .addGroup(newsFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(totalMoney))
                .addGap(26, 26, 26)
                .addComponent(mapContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        container.add(newsFeed, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");
        generateDeathExcel();
        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        
        try {
            PopulateDataInNewsFeed();
            container.add(newsFeed);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        
        dB4OUtil.storeSystem(system);
        
    }//GEN-LAST:event_logoutJButtonActionPerformed
    
    private void PopulateDataInNewsFeed() throws FileNotFoundException, IOException{
        BufferedReader reader = null;
        File file = new File("./Death.csv");
        if(!file.exists())
            System.out.println("File not found at the path specified: "+"./Death.csv");
        try { 
            reader = new BufferedReader(new FileReader(file));
        } catch (FileNotFoundException ex) {
            return;
        }
        
        ArrayList<String[]> list=new ArrayList<>();
        String line="";
        while((line=reader.readLine()) !=null){
            String[] rows = line.split(",");
            list.add(rows);
        }
        list.remove(0);
        int totalRevenue=0;
        for(String[] row : list){
            totalRevenue+=Integer.parseInt(row[9]);
        }
        
        totalDeaths.setText(String.valueOf(list.size()));
        totalMoney.setText(String.valueOf(totalRevenue));
        String acc=accidentProneArea(list);
        accidentProne.setText(acc);
        String crime=crimeProneArea(list);
        crimeProne.setText(crime);
        populateMap(list);
    }
    
    public ImageIcon displayPicture(String fileName){
        ImageIcon i = null;
        try{
            i= new ImageIcon(ImageIO.read(new File(fileName)));
            Image imageObj = i.getImage();
            Image newImage = imageObj.getScaledInstance(20, 40, java.awt.Image.SCALE_SMOOTH);
            i = new ImageIcon(newImage);
        }
        catch(Exception e){
            System.out.println(e);
        }
        return i;
    }
    
    public void populateMap(ArrayList<String[]> list){
        String[] loc={"NorthStation","Longwood","SouthStation","Lechmere","Park Street","BackBay","TremontStreet","RoxBury"};
        ArrayList<String> locList= new ArrayList<>();
        for(String s:loc){
            locList.add(s);
        }
        Random r=new Random();
        for(Component jpanel : mapContainer.getComponents()){
            if(jpanel instanceof JPanel){
                ((JPanel) jpanel).removeAll();
            }
            
        }
        for(String[] row:list){
            String location=row[8];
            if(locList.contains(location)){
                JLabel label=new JLabel();
                label.setSize(20,40);
                label.setIcon(displayPicture("Icons/deadBody.png"));
                JPanel panel = null;
                switch(location){
                    case "NorthStation":
                        panel=northStationJPanel;
                        break;
                    case "Longwood":
                        panel=longwood;
                        break;
                    case "SouthStation":
                        panel=southStationJPanel;
                        break;
                    case "Lechmere":
                        panel=lechmere;
                        break;
                    case "Park Street":
                        panel=parkStreet;
                        break;
                    case "BackBay":
                        panel=backBay;
                        break;
                    case "TremontStreet":
                        panel=tremontStreet;
                        break;
                    case "RoxBury":
                        panel=roxburyJPanel;
                        break;  
                }
                
                int min=panel.getWidth();
                int max=panel.getHeight();
                int x=r.nextInt(min-20);
                int y=r.nextInt(Math.abs(max-40));
                label.setLocation(x, y);
                panel.add(label);
                
            }
        }
    }
    
    public String accidentProneArea(ArrayList<String[]> listFile){
         HashMap<String, ArrayList<String>> hm=new HashMap<>();
         for(String[] row: listFile){
            if(row[10].equalsIgnoreCase("accident")){
                String location=row[8];
                if(hm.containsKey(location)){
                    hm.get(location).add(row[0]);
                }else{
                    ArrayList<String> list= new ArrayList<>();
                    list.add(row[0]);
                    hm.put(location, list);
                }
            }
         }
         int max=0;
         String maxLocation="";
         for(Map.Entry<String, ArrayList<String>> entry: hm.entrySet()){
             if(entry.getValue().size()>max){
                 max=entry.getValue().size();
                 maxLocation=entry.getKey();
             }
         }
         return maxLocation;
    }
    
    public String crimeProneArea(ArrayList<String[]> listFile){
         HashMap<String, ArrayList<String>> hm=new HashMap<>();
         for(String[] row: listFile){
            if(row[10].equalsIgnoreCase("crime")){
                String location=row[8];
                if(hm.containsKey(location)){
                    hm.get(location).add(row[0]);
                }else{
                    ArrayList<String> list= new ArrayList<>();
                    list.add(row[0]);
                    hm.put(location, list);
                }
            }
         }
         int max=0;
         String maxLocation="";
         for(Map.Entry<String, ArrayList<String>> entry: hm.entrySet()){
             if(entry.getValue().size()>max){
                 max=entry.getValue().size();
                 maxLocation=entry.getKey();
             }
         }
         return maxLocation;
    }
    
    private void generateDeathExcel(){
        File file = new File("./Death.csv");
        FileWriter writer=null;
        if(file.exists()){
            file.delete();
        }
        try {
            file.createNewFile();
        } catch (IOException ex) {
            System.out.println(ex);
        }
        System.out.println("New Death File Created");
        try {
            writer = new FileWriter(file);
            writer.append("DeathId, fName, lName, gender, age, monthlySalary, noofDependents, ReasonOfDeath, locationOfDeath, amountAssigned, generalReasonOfDeath");
            writer.append("\n");
        } catch (IOException ex) {
            System.out.println(ex);
        }
        
        for(DeadPerson dp:system.getDeadpeople().getDeadPeople()){
            try {
                String s="";
                s+=dp.toString()+",";
                s+=dp.getfName()+",";
                s+=dp.getlName()+",";
                s+=dp.getGender()+",";
                s+=dp.getAge()+",";
                s+=dp.getMonthlySalary()+",";
                s+=dp.getNoOfDependents()+",";
                s+=dp.getReasonOfDeath()+",";
                s+=dp.getLocationOfDeath()+",";
                s+=dp.getamountAssigned()+",";
                s+=dp.getGeneralReasonOfDeath()+",";
                writer.append(s);
                writer.append("\n");
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
        try {
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise inEnterprise=null;
        Organization inOrganization=null;

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            container.remove(newsFeed);
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("workArea",userAccount.getRole().createWorkArea(container,inEnterprise,inOrganization,userAccount,system));
            layout.next(container);
        }

        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
    }//GEN-LAST:event_loginJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accidentProne;
    private javax.swing.JPanel backBay;
    private javax.swing.JPanel container;
    private javax.swing.JLabel crimeProne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel lechmere;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPanel longwood;
    private javax.swing.JPanel mapContainer;
    private javax.swing.JPanel newsFeed;
    private javax.swing.JPanel northStationJPanel;
    private javax.swing.JPanel parkStreet;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel roxburyJPanel;
    private javax.swing.JPanel southStationJPanel;
    private javax.swing.JLabel totalDeaths;
    private javax.swing.JLabel totalMoney;
    private javax.swing.JPanel tremontStreet;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
