/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeathCertificateCheckerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AnalysisOrganization;
import Business.Organization.IncomeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saboo
 */
public class EntryDCTRoleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntryDCTRoleJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    public EntryDCTRoleJPanel(JPanel container,Organization organization, UserAccount account, EcoSystem business) {
        initComponents();
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;
         DCTvalue.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mortuaryStatusBtn = new javax.swing.JButton();
        deathStatsBtn = new javax.swing.JButton();
        DCTvalue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        gvtRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        mortuaryStatusBtn.setBackground(new java.awt.Color(51, 153, 255));
        mortuaryStatusBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mortuaryStatusBtn.setText("Mortuary Request");
        mortuaryStatusBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mortuaryStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortuaryStatusBtnActionPerformed(evt);
            }
        });

        deathStatsBtn.setBackground(new java.awt.Color(51, 153, 255));
        deathStatsBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deathStatsBtn.setText("DeathStats Request Status");
        deathStatsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deathStatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathStatsBtnActionPerformed(evt);
            }
        });

        DCTvalue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DCTvalue.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Death Certification Team");

        gvtRequestBtn.setBackground(new java.awt.Color(51, 153, 255));
        gvtRequestBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gvtRequestBtn.setText("Government Request Status");
        gvtRequestBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gvtRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvtRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DCTvalue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(mortuaryStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gvtRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(deathStatsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DCTvalue)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mortuaryStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gvtRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deathStatsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mortuaryStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortuaryStatusBtnActionPerformed
        // TODO add your handling code here:
        MortuaryStatusJPanel mortuaryStatusJPanel=new MortuaryStatusJPanel(container,organization,account,business);
        container.add("mortuaryStatusJPanel",mortuaryStatusJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_mortuaryStatusBtnActionPerformed

    private void deathStatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathStatsBtnActionPerformed
        // TODO add your handling code here:
        Organization org=null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof AnalysisOrganization){
                        org=o;
                    }
                }
            }
        }
        if(org.getWorkQueue().getWorkRequestList().size() == 0){
            JOptionPane.showMessageDialog(null, "No Govt Requests currently");
            return;
        }
        if(org!=null){
            DeathStatsStatusJPanel deathStatsStatusJPanel=new DeathStatsStatusJPanel(container,org,account,business);
            container.add("deathStatsStatusJPanel",deathStatsStatusJPanel);
            CardLayout layout=(CardLayout)container.getLayout();
            layout.next(container);
        }else{
            JOptionPane.showMessageDialog(null, "No Organizations created for DeathStats !!");
            return;
        }
    }//GEN-LAST:event_deathStatsBtnActionPerformed

    private void gvtRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvtRequestBtnActionPerformed
        // TODO add your handling code here:
        Organization org=null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    System.out.println(o.getName());
                    if(o instanceof IncomeOrganization){
                        org=o;
                    }
                }
            }
        }
        if(org.getWorkQueue().getWorkRequestList().size() == 0){
            JOptionPane.showMessageDialog(null, "No Govt Requests currently");
            return;
        }
        GovernmentStatusJPanel governmentStatusJPanel=new GovernmentStatusJPanel(container,org,account,business);
        container.add("governmentStatusJPanel",governmentStatusJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_gvtRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DCTvalue;
    private javax.swing.JButton deathStatsBtn;
    private javax.swing.JButton gvtRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mortuaryStatusBtn;
    // End of variables declaration//GEN-END:variables
}
