/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeathCertificateCheckerRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Enterprise.DeathStatsEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentAuthorityEnterprise;
import Business.Network.Network;
import Business.Organization.AnalysisOrganization;
import Business.Organization.IncomeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeathRegisterRequest;
import Business.WorkQueue.DeathStatTransferWorkRequest;
import Business.WorkQueue.GovtMoneyRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author saboo
 */
public class ProcessingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form processingJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    private DeadPerson dp;
    private WorkRequest requestMain;
    public ProcessingJPanel(JPanel container, Organization organization, UserAccount account, EcoSystem business, DeadPerson dp, WorkRequest requestMain) {
        initComponents();
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;
        this.dp=dp;
        this.requestMain = requestMain;
        deathStatsTransfer.setEnabled(true);
        gvtTransferBtn.setEnabled(true);
        populateData();
    }
    
    private void populateData(){
        fname.setText(dp.getfName());
        lname.setText(dp.getlName());
        age.setText(String.valueOf(dp.getAge()));
        String gender= dp.getGender();
        if(gender =="M"){
            rbtnM.setSelected(true);
        }else{
            rbtnF.setSelected(true);
        }
        txtLocation.setText(dp.getLocationOfDeath());
        txtDependants.setText(String.valueOf(dp.getNoOfDependents()));
        txtReason.setText(dp.getReasonOfDeath());
        txtIncome.setText(String.valueOf(dp.getMonthlySalary()));
        if(dp.getNoOfDependents()>2){
            deathStatsTransfer.setEnabled(false);
        }
        else{
            gvtTransferBtn.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        deathStatsTransfer = new javax.swing.JButton();
        gvtTransferBtn = new javax.swing.JButton();
        rbtnM = new javax.swing.JRadioButton();
        rbtnF = new javax.swing.JRadioButton();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDependants = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIncome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Registered  Death Details");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setText("Last Name:");

        lname.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        lname.setForeground(new java.awt.Color(102, 153, 255));
        lname.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setText("Age:");

        age.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        age.setForeground(new java.awt.Color(102, 153, 255));
        age.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setText("Location of Death:");

        txtLocation.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(102, 153, 255));
        txtLocation.setEnabled(false);

        deathStatsTransfer.setBackground(new java.awt.Color(102, 153, 255));
        deathStatsTransfer.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        deathStatsTransfer.setText("Transfer To DeathStats");
        deathStatsTransfer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deathStatsTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathStatsTransferActionPerformed(evt);
            }
        });

        gvtTransferBtn.setBackground(new java.awt.Color(102, 153, 255));
        gvtTransferBtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        gvtTransferBtn.setText("Transfer To Government");
        gvtTransferBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gvtTransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvtTransferBtnActionPerformed(evt);
            }
        });

        rbtnM.setForeground(new java.awt.Color(102, 153, 255));
        rbtnM.setText("M");
        rbtnM.setEnabled(false);
        rbtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMActionPerformed(evt);
            }
        });

        rbtnF.setForeground(new java.awt.Color(102, 153, 255));
        rbtnF.setText("F");
        rbtnF.setEnabled(false);
        rbtnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFActionPerformed(evt);
            }
        });

        fname.setEditable(false);
        fname.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        fname.setForeground(new java.awt.Color(102, 153, 255));
        fname.setEnabled(false);
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setText("No.of Dependants:");

        txtDependants.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtDependants.setForeground(new java.awt.Color(102, 153, 255));
        txtDependants.setEnabled(false);
        txtDependants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDependantsActionPerformed(evt);
            }
        });
        txtDependants.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDependantsKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setText("Annual Income:");

        txtIncome.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtIncome.setForeground(new java.awt.Color(102, 153, 255));
        txtIncome.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setText("Reason of Death:");

        txtReason.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txtReason.setForeground(new java.awt.Color(102, 153, 255));
        txtReason.setEnabled(false);

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/DeathCertificateCheckerRole/back.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lname)
                                        .addComponent(age)
                                        .addComponent(txtLocation)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(rbtnM)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbtnF))
                                        .addComponent(fname, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDependants)
                                        .addComponent(txtIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gvtTransferBtn)
                                .addGap(33, 33, 33)
                                .addComponent(deathStatsTransfer)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtnM)
                    .addComponent(rbtnF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDependants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gvtTransferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deathStatsTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deathStatsTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deathStatsTransferActionPerformed
        // TODO add your handling code here:
        requestMain.setMessage("Approved and sent for DeathStats analysis and research.");
        requestMain.setStatus("Approved");
        dp.setAmountDecided(true);
        
        DeathStatTransferWorkRequest req=new DeathStatTransferWorkRequest();
        req.setDeadPerson(dp);
        req.setSender(account);
        req.setMessage("Death Registerd for further analysis and Research");
        req.setStatus("Sent");
        
        Organization org = null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof DeathStatsEnterprise){
                    for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof AnalysisOrganization){
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(req);
            account.getWorkQueue().getWorkRequestList().add(req);
        }
        DeathStatsStatusJPanel deathStatsStatusJPanel=new DeathStatsStatusJPanel(container,org,account,business);
        container.add("deathStatsStatusJPanel",deathStatsStatusJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);

    }//GEN-LAST:event_deathStatsTransferActionPerformed

    private void rbtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMActionPerformed
        // TODO add your handling code here:
        rbtnF.setSelected(false);
    }//GEN-LAST:event_rbtnMActionPerformed

    private void rbtnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFActionPerformed
        // TODO add your handling code here:
        rbtnM.setSelected(false);
    }//GEN-LAST:event_rbtnFActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void txtDependantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDependantsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDependantsActionPerformed

    private void txtDependantsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDependantsKeyReleased
        // TODO add your handling code here:
        //        int dependants = Integer.parseInt(txtDependants.getText());
        //        if(dependants>2){
            //            txtIncome.setEditable(true);
            //            txtIncome.setEnabled(true);
            //        }
        //        if(!txtDependants.getText().matches("\\d+")) {
            //            JOptionPane.showMessageDialog(null,"Income is invalid.");
            //            return;
            //        }
    }//GEN-LAST:event_txtDependantsKeyReleased

    private void gvtTransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvtTransferBtnActionPerformed
        // TODO add your handling code here:
        requestMain.setMessage("Approved and sent for Govt.");
        requestMain.setStatus("Approved");
        GovtMoneyRequest request=new GovtMoneyRequest();
        request.setDeadPerson(dp);
        request.setSender(account);
        request.setMessage("Claim Request Sent for Approval");
        request.setStatus("Pending");
        
        Organization org = null;
        for(Network n: business.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof GovernmentAuthorityEnterprise){
                    for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof IncomeOrganization){
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
//        WorkRequest req= org.getWorkQueue().getWorkRequestList().get(0).
        GovernmentStatusJPanel governmentStatusJPanel=new GovernmentStatusJPanel(container,org,account,business);
        container.add("governmentStatusJPanel",governmentStatusJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_gvtTransferBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        Component[] components = container.getComponents();
        for(Component c :components){
            if(c instanceof MortuaryStatusJPanel){
                MortuaryStatusJPanel mortuaryStatus = (MortuaryStatusJPanel)c;
                mortuaryStatus.populateRequestTable();
            }
        }
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deathStatsTransfer;
    private javax.swing.JTextField fname;
    private javax.swing.JButton gvtTransferBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton rbtnF;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JTextField txtDependants;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtReason;
    // End of variables declaration//GEN-END:variables
}
