/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.MortuaryRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saboo
 */
public class EntryMortuaryRoleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntryMortuaryRoleJPanel1
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    private Enterprise enterprise;
    public EntryMortuaryRoleJPanel(JPanel container,Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business) {
        initComponents();
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;
        this.enterprise=enterprise;
        mortuarervalue.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportDeathBtn = new javax.swing.JButton();
        checkStatusBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mortuarervalue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        reportDeathBtn.setBackground(new java.awt.Color(102, 153, 255));
        reportDeathBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        reportDeathBtn.setText("Report Death");
        reportDeathBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportDeathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportDeathBtnActionPerformed(evt);
            }
        });

        checkStatusBtn.setBackground(new java.awt.Color(102, 153, 255));
        checkStatusBtn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkStatusBtn.setText("Check Status");
        checkStatusBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStatusBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Mortuarer");

        mortuarervalue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mortuarervalue.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mortuarervalue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(checkStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(reportDeathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mortuarervalue))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportDeathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportDeathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportDeathBtnActionPerformed
        // TODO add your handling code here:
        RegisterDeadJPanel registerDeadJPanel=new RegisterDeadJPanel(container,enterprise,organization,account,business);
        container.add("manageEnterpriseAdminJPanel",registerDeadJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_reportDeathBtnActionPerformed

    private void checkStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusBtnActionPerformed
        // TODO add your handling code here:
        if(business.getDeadpeople().getDeadPeople().size()==0){
            JOptionPane.showMessageDialog(null, "No Deaths Recorded");
                 return;
        }
        DeadStatusJPanel deadStatusJPanel=new DeadStatusJPanel(container,organization,account,business);
        container.add("manageEnterpriseAdminJPanel",deadStatusJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_checkStatusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkStatusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mortuarervalue;
    private javax.swing.JButton reportDeathBtn;
    // End of variables declaration//GEN-END:variables
}
