/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeathStatAnalystRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rajat
 */

public class EntryAnalystJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntryAnalystJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    public EntryAnalystJPanel(JPanel container, Organization organization, UserAccount account, EcoSystem business) {
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;
        initComponents();
        AnalystName.setText(account.getEmployee().getName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        analysDeathButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AnalystName = new javax.swing.JLabel();
        crimeRequestsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        analysDeathButton.setBackground(new java.awt.Color(102, 153, 255));
        analysDeathButton.setText("Analyse Deaths");
        analysDeathButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analysDeathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysDeathButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome DeathStats Analyst:");

        AnalystName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AnalystName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnalystName.setText("<value>");

        crimeRequestsButton.setBackground(new java.awt.Color(102, 153, 255));
        crimeRequestsButton.setText("Crime Requests");
        crimeRequestsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crimeRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeRequestsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(analysDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crimeRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnalystName)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(AnalystName, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analysDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crimeRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void analysDeathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysDeathButtonActionPerformed
        // TODO add your handling code here:
        AnalyseDeathJPanel analyseDeathJPanel=new AnalyseDeathJPanel(container,organization,account,business);
        container.add("analyseDeathPanel",analyseDeathJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_analysDeathButtonActionPerformed

    private void crimeRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeRequestsButtonActionPerformed
        // TODO add your handling code here:
        CrimeRequestJPanel crj=new CrimeRequestJPanel(container,organization,account,business);
        container.add("CrimeRequestJPanel",crj);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_crimeRequestsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnalystName;
    private javax.swing.JButton analysDeathButton;
    private javax.swing.JButton crimeRequestsButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
