/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CrimeCheckerRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.PoliceMan.PoliceMan;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JPanel;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajat
 */
public class CrimeCheckerEntryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CrimeCheckerEntryJPanel
     */    
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    private Enterprise enterprise;
    public CrimeCheckerEntryJPanel(JPanel container, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business) throws IOException {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.organization=organization;
        this.account=account;
        this.business=business;
        populateCrimeChecker();
        puttingImage();
    }
    
    public void populateCrimeChecker(){
        crimeCheckerName.setText(account.getEmployee().getName());
    }
    
    public void puttingImage(){
        int noOfPolice=0;
        if(business.getHashPolice()!=null){
            for(Map.Entry<String, ArrayList<PoliceMan>> entry: business.getHashPolice().entrySet()){
                noOfPolice+=entry.getValue().size();
            }
            policeCount.setText(String.valueOf(noOfPolice));
            try{
                ImageIcon i = new ImageIcon(ImageIO.read(new File("crimeChecker.jpg")));
                Image imageObj = i.getImage();
                Image newImage = imageObj.getScaledInstance(250, 250, java.awt.Image.SCALE_SMOOTH);
                i = new ImageIcon(newImage);
                crimeImgae.setIcon(i);
            }
            catch(Exception e){
                System.out.println(e);
            }
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        crimeCheckerName = new javax.swing.JLabel();
        analysDeathButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        policeCount = new javax.swing.JLabel();
        sendAlertMail = new javax.swing.JButton();
        crimeImgae = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Crime Checker:");

        crimeCheckerName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crimeCheckerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crimeCheckerName.setText("<value>");

        analysDeathButton.setBackground(new java.awt.Color(102, 153, 255));
        analysDeathButton.setText("View Crime Cases");
        analysDeathButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analysDeathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysDeathButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PoliceMan deployed until now");

        policeCount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        policeCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        policeCount.setText("<value>");

        sendAlertMail.setBackground(new java.awt.Color(102, 153, 255));
        sendAlertMail.setText("Send Alert Mail");
        sendAlertMail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendAlertMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAlertMailActionPerformed(evt);
            }
        });

        crimeImgae.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crimeImgae.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crimeImgae.setText("<value>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(analysDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(sendAlertMail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crimeCheckerName))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policeCount)
                .addGap(131, 131, 131)
                .addComponent(crimeImgae, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(crimeCheckerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analysDeathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendAlertMail, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(policeCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crimeImgae, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void analysDeathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysDeathButtonActionPerformed
        // TODO add your handling code here:
        CrimeListsJPanel crimeJPanel=new CrimeListsJPanel(container,organization,account,business);
        container.add("crimeListJPanel",crimeJPanel);
        CardLayout layout=(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_analysDeathButtonActionPerformed
    
    private String CrimeProneArea(){
        HashMap<String, ArrayList<DeadPerson>> hm=new HashMap<>();
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("crime")){
                    String location =dp.getLocationOfDeath();
                    if(hm.containsKey(location)){
                        hm.get(location).add(dp);
                    }else{
                        ArrayList<DeadPerson> list= new ArrayList<>();
                        list.add(dp);
                        hm.put(location, list);
                    }
                }
            }
        }
        int max=0;
        String maxLocation="";
        for(Map.Entry<String, ArrayList<DeadPerson>> entry: hm.entrySet()){
            if(entry.getValue().size()>max){
                max=entry.getValue().size();
                maxLocation=entry.getKey();
            }
        }
        return maxLocation;
    }
    
    private void SendMail(String toMail){
        String to = toMail;
        String from = "deathstats2018@gmail.com";
        String host = "smtp.gmail.com";
        Properties properties = new Properties();

        // Setup mail server
        properties.put("mail.smtp.host", host);
        properties.put("mai.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.port", "587");
        properties.setProperty("mail.smtp.user", from);
        properties.setProperty("mail.smtp.password", "December@2018");
        properties.setProperty("mail.smtp.auth", "true"); 
        
        Session session = Session.getDefaultInstance(properties, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("deathstats2018@gmail.com", "December@2018");
            }
        });

        try {
           // Create a default MimeMessage object.
           MimeMessage message = new MimeMessage(session);
           // Set From: header field of the header.
           message.setFrom(new InternetAddress(from));
           // Set To: header field of the header.
           message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
           // Set Subject: header field
           message.setSubject("This is an alert Message!");

           // Send the actual HTML message, as big as you like
           message.setContent("<h1>This is a test mail. Current Crime prone area is "+CrimeProneArea()+" Please be safe !</h1>", "text/html");

           // Send message
           Transport.send(message);
           System.out.println("Sent message successfully....");
           JOptionPane.showMessageDialog(null, "Sent alert to all users !!");
        } catch (MessagingException mex) {
           mex.printStackTrace();
        }
    }
    
    private void sendAlertMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAlertMailActionPerformed
        // TODO add your handling code here:
        if(business.getEmailList().size()==0){
            JOptionPane.showMessageDialog(null, "No emails Registered with us !");
            return;
        }
        for(String toMail: business.getEmailList()){
            SendMail(toMail);
        }
        
    }//GEN-LAST:event_sendAlertMailActionPerformed

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analysDeathButton;
    private javax.swing.JLabel crimeCheckerName;
    private javax.swing.JLabel crimeImgae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel policeCount;
    private javax.swing.JButton sendAlertMail;
    // End of variables declaration//GEN-END:variables
}
