/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeathStatResearchRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Interface.DeathStatAnalystRole.AnalysingCurrentDeathJPanel;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saboo
 */
public class CalamityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccidentJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    public CalamityJPanel(JPanel container, Organization organization, UserAccount account, EcoSystem business) {
        initComponents();
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;
        populateAccidentDeathTable();
        accidentRateLabel.setVisible(false);
        CrimeproneLabel.setVisible(false);
    }
    
    public void populateAccidentDeathTable(){
        DefaultTableModel model = (DefaultTableModel) deathJTable.getModel();
        
        model.setRowCount(0);
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("calamity")){
                    Object[] row = new Object[5];
                    row[0] = dp.getfName();
                    row[1] = dp.getlName();
                    row[2] = dp.getAge();
                    row[3] = dp;
                    row[4] = dp.getLocationOfDeath();
                    model.addRow(row);
                } 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accidentRateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deathJTable = new javax.swing.JTable();
        crimeAreaBtn = new javax.swing.JButton();
        accidentRateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CrimeproneLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        accidentRateLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        accidentRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accidentRateLabel.setText("Deaths Due to Accidents");

        deathJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "DeathID", "Location of Death"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deathJTable);

        crimeAreaBtn.setBackground(new java.awt.Color(102, 153, 255));
        crimeAreaBtn.setText("Get Calamity Prone Area");
        crimeAreaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crimeAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeAreaBtnActionPerformed(evt);
            }
        });

        accidentRateBtn.setBackground(new java.awt.Color(102, 153, 255));
        accidentRateBtn.setText("Get Calamity Rate");
        accidentRateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accidentRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidentRateBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deaths Due to Natural Calamity");

        CrimeproneLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CrimeproneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrimeproneLabel.setText("Deaths Due to Crime");

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/DeathCertificateCheckerRole/back.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CrimeproneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(accidentRateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(crimeAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(accidentRateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accidentRateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(crimeAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(accidentRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CrimeproneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crimeAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeAreaBtnActionPerformed
        // TODO add your handling code here:
        
        HashMap<String, ArrayList<DeadPerson>> hm=new HashMap<>();
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("calamity")){
                    String location =dp.getLocationOfDeath();
                    if(hm.containsKey(location)){
                        hm.get(location).add(dp);
                    }else{
                        ArrayList<DeadPerson> list= new ArrayList<>();
                        list.add(dp);
                        hm.put(location, list);
                    }
                }
            }
        }
        int max=0;
        String maxLocation="";
        for(Map.Entry<String, ArrayList<DeadPerson>> entry: hm.entrySet()){
            if(entry.getValue().size()>max){
                max=entry.getValue().size();
                maxLocation=entry.getKey();
            }
        }
        CrimeproneLabel.setText("The Natural Calamity Prone Area is " + maxLocation.toUpperCase() + " Please take preventive measures.");
        CrimeproneLabel.setVisible(true);
        
       
    }//GEN-LAST:event_crimeAreaBtnActionPerformed

    private void accidentRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidentRateBtnActionPerformed
        // TODO add your handling code here:
       double totalDeaths = business.getDeadpeople().getDeadPeople().size();
       double accidentCount =0;
       double accidentPercentage =0;
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("Calamity")){
                   accidentCount++; 
                }
            }
        }
        accidentPercentage = (accidentCount/totalDeaths)*100;
        DecimalFormat df = new DecimalFormat("####0.00");
        accidentRateLabel.setText("The Accident Rate is " + df.format(accidentPercentage) +"%");
        accidentRateLabel.setVisible(true);
    }//GEN-LAST:event_accidentRateBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrimeproneLabel;
    private javax.swing.JButton accidentRateBtn;
    private javax.swing.JLabel accidentRateLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton crimeAreaBtn;
    private javax.swing.JTable deathJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
