/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeathStatResearchRole;

import Business.DeadPerson.DeadPerson;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saboo
 */
public class DieasesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DieasesJPanel
     */
    private JPanel container;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    public DieasesJPanel(JPanel container, Organization organization, UserAccount account, EcoSystem business) {
        initComponents();
        this.container=container;
        this.organization = organization;
        this.account = account;
        this.business = business;       
        populateAccidentDeathTable();
        accidentRateLabel.setVisible(false);
        CrimeproneLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateAccidentDeathTable(){
        DefaultTableModel model = (DefaultTableModel) deathJTable.getModel();
        
        model.setRowCount(0);
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("Diseases")){
                    Object[] row = new Object[5];
                    row[0] = dp.getfName();
                    row[1] = dp.getlName();
                    row[2] = dp.getAge();
                    row[3] = dp;
                    row[4] = dp.getNoOfDependents();
                    model.addRow(row);
                } 
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deathJTable = new javax.swing.JTable();
        affectedBtn = new javax.swing.JButton();
        DieasesRateBtn = new javax.swing.JButton();
        accidentRateLabel = new javax.swing.JLabel();
        CrimeproneLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deaths Due To Dieases");

        deathJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "DeathID", "Dependants of Death"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deathJTable);

        affectedBtn.setBackground(new java.awt.Color(102, 153, 255));
        affectedBtn.setText("No. of People Can be Affected");
        affectedBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        affectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affectedBtnActionPerformed(evt);
            }
        });

        DieasesRateBtn.setBackground(new java.awt.Color(102, 153, 255));
        DieasesRateBtn.setText("Get Dieases Rate");
        DieasesRateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DieasesRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DieasesRateBtnActionPerformed(evt);
            }
        });

        accidentRateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accidentRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accidentRateLabel.setText("Deaths Due to Accidents");

        CrimeproneLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CrimeproneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrimeproneLabel.setText("Deaths Due to Crime");

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/DeathCertificateCheckerRole/back.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(403, 403, 403)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(82, 82, 82)
                    .addComponent(affectedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83)
                    .addComponent(DieasesRateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrimeproneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accidentRateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(affectedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DieasesRateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(CrimeproneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(accidentRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void affectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affectedBtnActionPerformed
        // TODO add your handling code here:
        int maxDependants =0;
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("Diseases")){
                    maxDependants =dp.getNoOfDependents()+maxDependants;
                }
            }
        }
       
        CrimeproneLabel.setText("The Total Number of People Affected are: " + maxDependants + " Dead Dependants team will be looking for thier Health");
        CrimeproneLabel.setVisible(true);

    }//GEN-LAST:event_affectedBtnActionPerformed

    private void DieasesRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DieasesRateBtnActionPerformed
        // TODO add your handling code here:
        double totalDeaths = business.getDeadpeople().getDeadPeople().size();
        double accidentCount =0;
        double accidentPercentage =0;
        for (DeadPerson dp: business.getDeadpeople().getDeadPeople()){
            if(dp.getGeneralReasonOfDeath()!=null){
                if(dp.getGeneralReasonOfDeath().equalsIgnoreCase("Diseases")){
                    accidentCount++;
                }
            }
        }
        accidentPercentage = (accidentCount/totalDeaths)*100;
        DecimalFormat df = new DecimalFormat("####0.00");
        accidentRateLabel.setText("The Diseases Rate is " + df.format(accidentPercentage) +"%");
        accidentRateLabel.setVisible(true);
    }//GEN-LAST:event_DieasesRateBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrimeproneLabel;
    private javax.swing.JButton DieasesRateBtn;
    private javax.swing.JLabel accidentRateLabel;
    private javax.swing.JButton affectedBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable deathJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
